
# compile arguments
CFLAGS += -c -g -Wall -Wvla

# source files
SOURCES = GenericHashTable.c tester.c

# a rule for generating object files given their c files
compile:
	@echo "Compiling..."
	gcc $(CFLAGS) $(SOURCES)

clean:
	rm -rf *s *o
